door_dash:
jump_club:
  centerLocation:
    ==: org.bukkit.Location
    world: world
    x: -208.0
    y: 84.0
    z: 15.0
roll_out:
  centerLocation:
    ==: org.bukkit.Location
    world: world
    x: -208.0
    y: 84.0
    z: 15.0