name: Chess
version: 1.0
author: fritzpal
api-version: 1.16
main: me.fritzpal.minecraftChess.Main
commands:
  chess:
    description: Start a game of chess
    usage: /chess <whitePlayer> <blackPlayer>
